import { Chapter } from "../../../types/content";

export const greatAthletes: Chapter = {
  id: "great-athletes",
  slug: "great-athletes",
  number: 1,
  semester: 1,
  title: "Great Athletes",
  theme: "Sports",
  question: "What makes an athlete great?",
  overview:
    "This chapter invites students to explore the qualities that define great athletes. Through descriptive writing, students learn to paint vivid pictures of people using precise adjectives, adverbs, and the simple present tense. By examining real and fictional athletes, students develop the ability to describe appearance, personality, habits, and achievements in engaging detail.",
  estimatedTime: "8 hours",
  skills: ["reading", "writing", "speaking", "listening"],
  textType: "descriptive",
  languageFocus: ["simple present", "adjectives", "adverbs"],
  objectives: [
    {
      id: "ga-obj-1",
      description: "Identify and use descriptive adjectives to describe people's appearance and personality.",
      level: "remember",
    },
    {
      id: "ga-obj-2",
      description: "Write a coherent descriptive paragraph about an athlete using simple present tense.",
      level: "apply",
    },
    {
      id: "ga-obj-3",
      description: "Analyze how adverbs of manner add detail and depth to descriptive writing.",
      level: "analyze",
    },
    {
      id: "ga-obj-4",
      description: "Evaluate the effectiveness of a descriptive text based on clarity and vividness.",
      level: "evaluate",
    },
  ],
  lessons: [
    {
      id: "ga-lesson-1",
      slug: "describing-people",
      number: 1,
      title: "Describing People",
      description:
        "Students learn to use adjectives and adverbs to describe an athlete's physical appearance and personality traits.",
      duration: 50,
      objectives: [
        {
          id: "ga-l1-obj-1",
          description: "Use at least 8 descriptive adjectives in a paragraph.",
          level: "apply",
        },
        {
          id: "ga-l1-obj-2",
          description: "Distinguish between adjectives of opinion and fact.",
          level: "understand",
        },
      ],
      vocabulary: [
        { word: "athletic", definition: "physically fit and strong", example: "She has an athletic build.", phonetic: "/æθˈlɛtɪk/" },
        { word: "determined", definition: "having firm resolve to achieve a goal", example: "He is determined to win the championship.", phonetic: "/dɪˈtɜːrmɪnd/" },
        { word: "resilient", definition: "able to recover quickly from difficulties", example: "The resilient athlete bounced back after her injury.", phonetic: "/rɪˈzɪliənt/" },
        { word: "disciplined", definition: "showing self-control and training", example: "A disciplined runner trains every morning.", phonetic: "/ˈdɪsəplɪnd/" },
        { word: "charismatic", definition: "having a charming and inspiring personality", example: "The charismatic captain motivated the entire team.", phonetic: "/ˌkærɪzˈmætɪk/" },
      ],
      languageFocus: ["adjectives of opinion vs. fact", "adjective order", "adverbs of manner"],
      conceptExplanation:
        "When we describe a person, we use adjectives to give details about appearance, personality, and behavior. Adjectives of opinion (beautiful, talented, amazing) express our personal feelings, while adjectives of fact (tall, 25 years old, Indonesian) can be proven. The order of adjectives in English follows a specific pattern: opinion, size, age, shape, color, origin, material, purpose.\n\nAdverbs of manner (quickly, carefully, gracefully) tell us how someone does something. They usually come after the main verb or at the end of a sentence. For example, 'She runs quickly' or 'He trained carefully for the competition.'",
      examples: [
        "Lia is a talented and determined tennis player. She trains hard every day and never gives up during matches.",
        "The tall, athletic basketball player moves gracefully across the court. He dribbles skillfully and shoots accurately.",
      ],
      modelText:
        "Rina Hartono is one of the most inspiring swimmers in the country. She has a lean, athletic build and long arms that cut through the water with remarkable ease. Rina is fiercely competitive and deeply disciplined; she arrives at the pool before sunrise every single day. Her teammates describe her as generous and encouraging, always offering tips after practice. Despite winning numerous gold medals, Rina remains humble and focused. She believes that greatness comes not from trophies but from the daily commitment to improving oneself. Young swimmers across the region look up to her as a role model.",
      activities: [
        {
          id: "ga-l1-act-1",
          type: "vocabulary",
          title: "Adjective Brainstorm",
          instruction: "Match each adjective in the box with the correct category: opinion, fact, or behavior.",
          content: {
            type: "vocabulary",
            words: [
              { word: "tall", definition: "fact — can be measured", example: "He is 190 cm tall." },
              { word: "brilliant", definition: "opinion — a personal judgment", example: "She is a brilliant strategist." },
              { word: "sprint", definition: "behavior — describes how someone acts", example: "She sprints to the finish line." },
            ],
          },
          answerKey: {
            answers: { tall: "fact", brilliant: "opinion", sprint: "behavior" },
            explanation: "Tall is a measurable fact. Brilliant is a subjective opinion. Sprint describes an action or behavior.",
          },
          duration: 10,
          level: "remember",
        },
        {
          id: "ga-l1-act-2",
          type: "fill-blank",
          title: "Describing an Athlete",
          instruction: "Complete the paragraph by filling in the blanks with suitable adjectives.",
          content: {
            type: "fill-blank",
            sentence: "The ___ swimmer trains ___ every morning. She is ___ in the water and ___ out of it. Her ___ attitude inspires her teammates.",
            blanks: [
              { id: "b1", position: 1, acceptedAnswers: ["athletic", "talented", "skilled", "gifted"] },
              { id: "b2", position: 2, acceptedAnswers: ["diligently", "hard", "early", "faithfully"] },
              { id: "b3", position: 3, acceptedAnswers: ["graceful", "fast", "quick", "swift"] },
              { id: "b4", position: 4, acceptedAnswers: ["calm", "focused", "relaxed", "confident"] },
              { id: "b5", position: 5, acceptedAnswers: ["positive", "determined", "inspiring", "encouraging"] },
            ],
            explanation: "The blanks require adjectives or adverbs that logically describe an athlete and her training habits.",
          },
          answerKey: {
            answers: { b1: "athletic", b2: "diligently", b3: "graceful", b4: "focused", b5: "determined" },
            explanation: "Any combination of appropriate adjectives and adverbs that creates a coherent paragraph is acceptable.",
          },
          duration: 15,
          level: "understand",
        },
        {
          id: "ga-l1-act-3",
          type: "discussion",
          title: "My Athletic Role Model",
          instruction: "Discuss with a partner: Who is your favorite athlete and why?",
          content: {
            type: "discussion",
            prompt: "Think of an athlete you admire. What three adjectives would you use to describe them? Why did you choose those words?",
            thinkingTime: 3,
            pairInstruction: "Share your athlete with your partner and explain your choices.",
            shareOutPrompt: "Which adjective was chosen by most pairs?",
          },
          answerKey: {
            answers: {},
            explanation: "Open-ended discussion. Look for students who use specific adjectives and provide reasons.",
            openEnded: true,
            lookFor: ["specific adjectives", "clear reasoning", "active listening"],
          },
          duration: 15,
          level: "understand",
        },
      ],
      teacherNotes: {
        objective: "Students will practice using descriptive adjectives and adverbs to characterize athletes.",
        time: "50 minutes",
        grouping: "Whole class introduction, individual work, pair discussion",
        teacherPrompt: "Ask students: What makes a famous athlete different from an ordinary person? Can you think of three words to describe your favorite athlete?",
        expectedResponse: "Students should list physical traits (strong, fast) and personality traits (determined, humble).",
        commonDifficulty: "Students often confuse adjectives with adverbs. Remind them that adjectives describe nouns, while adverbs describe verbs, adjectives, or other adverbs.",
        followUp: "Have students write a 5-sentence description of a family member as homework, using at least 3 adjectives and 2 adverbs.",
      },
    },
    {
      id: "ga-lesson-2",
      slug: "simple-present-athletes",
      number: 2,
      title: "Simple Present for Habits and Facts",
      description:
        "Students learn how the simple present tense is used in descriptive writing to describe habits, routines, and general facts about athletes.",
      duration: 50,
      objectives: [
        {
          id: "ga-l2-obj-1",
          description: "Use simple present to describe regular habits and routines.",
          level: "apply",
        },
        {
          id: "ga-l2-obj-2",
          description: "Identify simple present usage in descriptive paragraphs.",
          level: "understand",
        },
      ],
      vocabulary: [
        { word: "regimen", definition: "a strict training or diet plan", example: "She follows a strict training regimen.", phonetic: "/ˈrɛdʒɪmən/" },
        { word: "consistency", definition: "the quality of doing something regularly", example: "Her consistency in practice led to improvement.", phonetic: "/kənˈsɪstənsi/" },
        { word: "stamina", definition: "physical or mental endurance", example: "Marathon runners need incredible stamina.", phonetic: "/ˈstæmɪnə/" },
        { word: "dedication", definition: "commitment to a task or purpose", example: "His dedication to training is admirable.", phonetic: "/ˌdɛdɪˈkeɪʃən/" },
        { word: "technique", definition: "a way of carrying out a task skillfully", example: "Her swimming technique is flawless.", phonetic: "/tɛkˈniːk/" },
      ],
      languageFocus: ["simple present for habits", "third-person -s", "frequency adverbs"],
      conceptExplanation:
        "The simple present tense describes things that happen regularly, facts that are always true, and habits or routines. In descriptive writing about athletes, we use it to explain what they do on a daily basis. For example: 'She trains six days a week' or 'He drinks three liters of water every day.'\n\nWhen the subject is he, she, or it, we add -s or -es to the base verb: train becomes trains, study becomes studies, watch becomes watches. Frequency adverbs like always, usually, often, sometimes, and never help us describe how often an action occurs.",
      examples: [
        "Marcus trains twice a day. He wakes up at five in the morning and runs five kilometers before breakfast.",
        "The gymnast practices her routine every afternoon. She always stretches first and then works on her flips.",
      ],
      modelText:
        "Every morning at dawn, Kenji Tanaka laces up his running shoes and heads out the door. He trains six days a week, covering at least ten kilometers per session. Kenji rarely eats fast food and he always drinks plenty of water after training. On Sundays, he rests and reviews video footage of his races to improve his technique. He believes that consistency is the key to success, and he never misses a training session unless he is injured. His dedication has paid off: he consistently finishes in the top three at regional competitions.",
      activities: [
        {
          id: "ga-l2-act-1",
          type: "text-analysis",
          title: "Finding Simple Present in Context",
          instruction: "Read the paragraph and identify all verbs in the simple present tense. Discuss what each verb tells us about the athlete.",
          content: {
            type: "text-analysis",
            text: "Coach Amir wakes up at 4:30 every morning. He drinks a protein shake before heading to the gym. He trains his athletes for three hours and then reviews their performance on video. He always encourages them to push harder but also knows when to rest them. His athletes respect him because he always leads by example.",
            questions: [
              { id: "ta1-q1", question: "How many simple present verbs can you find in the text?", options: [{ id: "a", text: "5" }, { id: "b", text: "7" }, { id: "c", text: "9" }, { id: "d", text: "11" }], correctId: "c" },
              { id: "ta1-q2", question: "What does 'wakes up at 4:30' tell us about Coach Amir?", options: [{ id: "a", text: "He is lazy" }, { id: "b", text: "He is disciplined" }, { id: "c", text: "He is tired" }, { id: "d", text: "He is new" }], correctId: "b" },
            ],
          },
          answerKey: {
            answers: { "ta1-q1": "c", "ta1-q2": "b" },
            explanation: "The simple present verbs are: wakes, drinks, trains, reviews, encourages, knows, rests, respects, leads, heading (part of continuous form but contains present reference). The verb tells us about his daily routine, showing discipline.",
          },
          duration: 15,
          level: "analyze",
        },
        {
          id: "ga-l2-act-2",
          type: "fill-blank",
          title: "Frequency Adverb Exercise",
          instruction: "Complete each sentence with an appropriate frequency adverb.",
          content: {
            type: "fill-blank",
            sentence: "She ___ trains in the morning because she ___ has time in the evening. She ___ does yoga on Sundays. She ___ skips a training session.",
            blanks: [
              { id: "fa1", position: 1, acceptedAnswers: ["always", "usually", "often"] },
              { id: "fa2", position: 2, acceptedAnswers: ["never", "rarely", "seldom"] },
              { id: "fa3", position: 3, acceptedAnswers: ["always", "sometimes", "usually"] },
              { id: "fa4", position: 4, acceptedAnswers: ["never", "rarely", "hardly ever"] },
            ],
            explanation: "The frequency adverbs must match the context: she trains in the morning, has no time at night, does yoga on Sundays, and is too dedicated to skip training.",
          },
          answerKey: {
            answers: { fa1: "always", fa2: "never", fa3: "always", fa4: "never" },
            explanation: "The most logical answers show a dedicated athlete who trains regularly and never misses sessions.",
          },
          duration: 10,
          level: "apply",
        },
        {
          id: "ga-l2-act-3",
          type: "writing-task",
          title: "My Training Day",
          instruction: "Write a short paragraph (5-7 sentences) describing an athlete's typical training day using simple present tense and at least 2 frequency adverbs.",
          content: {
            type: "writing-task",
            context: "Imagine you are writing for a school sports magazine about a local athlete.",
            purpose: "To describe a training routine using simple present and frequency adverbs.",
            audience: "Fellow students who are interested in sports.",
            constraints: ["Use simple present tense", "Include at least 2 frequency adverbs", "Write 5-7 sentences", "Use at least 3 adjectives"],
            checklist: ["Simple present used correctly", "Frequency adverbs included", "Adjectives present", "Clear and coherent paragraph"],
          },
          answerKey: {
            answers: {},
            explanation: "Open-ended writing task.",
            openEnded: true,
            sampleResponse: "Lena trains every day after school. She always starts with a five-minute warm-up jog. She usually practices her serve for thirty minutes. She often stays late to work on her footwork. She rarely takes breaks because she is very determined.",
            lookFor: ["correct simple present forms", "appropriate frequency adverbs", "vivid adjectives"],
          },
          duration: 20,
          level: "apply",
        },
      ],
      teacherNotes: {
        objective: "Students will use simple present tense and frequency adverbs to describe athlete routines.",
        time: "50 minutes",
        grouping: "Whole class, pair work, individual writing",
        teacherPrompt: "Ask students to describe their own morning routine using simple present. Then extend this to describe an athlete's day.",
        expectedResponse: "Students can list their own habits and begin to describe a hypothetical athlete's routine.",
        commonDifficulty: "Forgetting the -s ending on third-person verbs. Drill this with quick oral practice before the writing task.",
        followUp: "Collect the writing tasks and provide feedback on tense consistency.",
      },
    },
    {
      id: "ga-lesson-3",
      slug: "writing-descriptive-text",
      number: 3,
      title: "Writing a Full Descriptive Text",
      description:
        "Students plan and write a complete descriptive text about an athlete, combining adjectives, adverbs, and simple present tense.",
      duration: 60,
      objectives: [
        {
          id: "ga-l3-obj-1",
          description: "Organize a descriptive text with a clear topic sentence and supporting details.",
          level: "apply",
        },
        {
          id: "ga-l3-obj-2",
          description: "Write a 150-word descriptive paragraph about an athlete.",
          level: "create",
        },
      ],
      vocabulary: [
        { word: "proportion", definition: "the relative size or scale of parts", example: "Her body proportions are ideal for gymnastics." },
        { word: "endurance", definition: "the ability to sustain prolonged effort", example: "Long-distance runners build great endurance." },
        { word: "remarkable", definition: "worthy of attention; extraordinary", example: "She has a remarkable talent for diving." },
        { word: "flawless", definition: "without any imperfections", example: "Her technique is nearly flawless." },
        { word: "acclaim", definition: "enthusiastic public praise", example: "She received international acclaim for her performance." },
      ],
      languageFocus: ["topic sentence", "supporting details", "cohesive devices (addition, contrast)"],
      conceptExplanation:
        "A descriptive text about a person follows a clear structure. It opens with a topic sentence that introduces the person being described. The body sentences provide details about appearance, personality, habits, and achievements using adjectives and adverbs. The concluding sentence summarizes the overall impression.\n\nCohesive devices like moreover, however, and in addition help connect ideas smoothly. For example: 'She is incredibly fast. Moreover, she never gives up during a race.'",
      examples: [
        "Topic sentence: Anouk is a remarkable volleyball player who combines power with elegance.\nBody: She is tall and athletic, with strong shoulders that help her spike the ball with devastating force. She trains hard every day and never misses practice.\nConclusion: Anouk's talent and dedication make her a true champion.",
      ],
      modelText:
        "Andi Wijaya is a young sprinter who has been making waves in the national athletics scene. He is lean and muscular, with powerful legs that propel him forward at extraordinary speed. Andi is known for his explosive starts; he reacts faster than almost anyone at the starting blocks. Off the track, he is quiet and thoughtful, often seen reading books about sports psychology. His coaches praise his discipline and his willingness to learn from every race, whether he wins or loses. Despite his growing fame, Andi remains grounded and focused on his goal of representing his country at the Asian Games. He believes that every training session brings him one step closer to his dream.",
      activities: [
        {
          id: "ga-l3-act-1",
          type: "ordering",
          title: "Paragraph Structure",
          instruction: "Arrange the following sentences in the correct order to form a descriptive paragraph about an athlete.",
          content: {
            type: "ordering",
            instruction: "Put the sentences in the correct order, starting with the topic sentence.",
            items: [
              { id: "o1", text: "She is the kind of athlete who inspires everyone around her.", correctPosition: 5 },
              { id: "o2", text: "Mira Johnson is one of the most talented swimmers in the country.", correctPosition: 1 },
              { id: "o3", text: "Her coaches say she has natural grace in the water.", correctPosition: 3 },
              { id: "o4", text: "She trains six hours a day and always pushes herself to improve.", correctPosition: 2 },
              { id: "o5", text: "Off the pool deck, Mira is generous and kind, always helping younger swimmers.", correctPosition: 4 },
            ],
            explanation: "The paragraph follows: topic sentence, supporting details about training, coach's observation, personality outside sport, and concluding summary.",
          },
          answerKey: {
            answers: { o1: "5", o2: "1", o3: "3", o4: "2", o5: "4" },
            explanation: "The correct order is: o2 (topic), o4 (training), o3 (coach's view), o5 (personality), o1 (conclusion).",
          },
          duration: 10,
          level: "understand",
        },
        {
          id: "ga-l3-act-2",
          type: "writing-task",
          title: "Write About Your Favorite Athlete",
          instruction: "Write a descriptive paragraph (100-150 words) about your favorite athlete.",
          content: {
            type: "writing-task",
            context: "A school newspaper is running a feature called 'Athletes We Admire.' You have been asked to contribute.",
            purpose: "To write a descriptive text that introduces an athlete to readers.",
            audience: "School community members who may not know this athlete.",
            constraints: ["Start with a clear topic sentence", "Use at least 5 adjectives", "Include at least 2 adverbs", "Use simple present tense", "End with a concluding sentence", "100-150 words"],
            checklist: ["Clear topic sentence", "Vivid adjectives used", "Adverbs included", "Simple present tense throughout", "Logical paragraph structure", "Word count met"],
            rubric: [
              { criterion: "Vocabulary range", levels: ["Limited", "Adequate", "Good", "Excellent"] },
              { criterion: "Grammar accuracy", levels: ["Frequent errors", "Some errors", "Mostly correct", "Accurate"] },
              { criterion: "Coherence", levels: ["Disorganized", "Somewhat clear", "Well-organized", "Highly effective"] },
            ],
          },
          answerKey: {
            answers: {},
            explanation: "Open-ended writing task assessed by rubric.",
            openEnded: true,
            sampleResponse: "David Chen is an extraordinary table tennis player who dominates every tournament he enters. He is quick and agile, with lightning-fast reflexes that allow him to return shots that seem impossible. David trains with intense focus every day, often staying at the practice hall until evening. He is also remarkably humble; despite winning numerous championships, he always credits his coaches and teammates. His ability to remain calm under pressure is what sets him apart from other players.",
            lookFor: ["topic sentence present", "adjective variety", "correct adverb placement", "coherent paragraph structure"],
          },
          duration: 25,
          level: "create",
        },
        {
          id: "ga-l3-act-3",
          type: "reflection",
          title: "Reflecting on Descriptive Writing",
          instruction: "Answer the following reflection questions about what you learned in this lesson.",
          content: {
            type: "reflection",
            prompts: [
              { id: "r1", question: "What was the most challenging part of writing a descriptive paragraph?", type: "difficulty" },
              { id: "r2", question: "How did using adjectives and adverbs change the quality of your writing?", type: "understanding" },
              { id: "r3", question: "In what other situations could you use descriptive writing?", type: "application" },
            ],
          },
          answerKey: {
            answers: {},
            explanation: "Reflection is subjective. Look for honest self-assessment and connections to real-life writing tasks.",
            openEnded: true,
          },
          duration: 10,
          level: "evaluate",
        },
      ],
      teacherNotes: {
        objective: "Students will produce a structured descriptive paragraph about an athlete.",
        time: "60 minutes",
        grouping: "Individual writing with peer review",
        teacherPrompt: "Walk students through the paragraph structure on the board. Model a short paragraph together before they write independently.",
        expectedResponse: "Students produce a paragraph with a topic sentence, 3-5 supporting details, and a concluding sentence.",
        commonDifficulty: "Students may write a list of sentences instead of a connected paragraph. Emphasize the use of cohesive devices.",
        followUp: "Organize a peer review session where students read each other's paragraphs and give feedback using a checklist.",
      },
    },
    {
      id: "ga-lesson-4",
      slug: "adverbs-of-manner",
      number: 4,
      title: "Adverbs of Manner in Action",
      description:
        "Students deepen their understanding of adverbs of manner and practice integrating them naturally into descriptive writing about athletes.",
      duration: 50,
      objectives: [
        {
          id: "ga-l4-obj-1",
          description: "Form adverbs from adjectives by adding -ly.",
          level: "remember",
        },
        {
          id: "ga-l4-obj-2",
          description: "Use adverbs of manner to enhance descriptions of how athletes perform.",
          level: "apply",
        },
        {
          id: "ga-l4-obj-3",
          description: "Distinguish between adjective and adverb usage in sentences.",
          level: "analyze",
        },
      ],
      vocabulary: [
        { word: "gracefully", definition: "in a smooth and elegant way", example: "She glides gracefully across the ice." },
        { word: "fiercely", definition: "in a strong and determined way", example: "He competes fiercely in every match." },
        { word: "precisely", definition: "in an exact and accurate way", example: "She serves the ball precisely where she aims." },
        { word: "relentlessly", definition: "in a way that never stops or gives up", example: "He trains relentlessly toward his goal." },
        { word: "effortlessly", definition: "in a way that requires no apparent effort", example: "She scores effortlessly from the free-throw line." },
      ],
      languageFocus: ["adverb formation (-ly)", "adverb placement", "adjective vs. adverb distinction"],
      conceptExplanation:
        "Adverbs of manner describe how an action is performed. Most are formed by adding -ly to the adjective: quick becomes quickly, graceful becomes gracefully. However, some adverbs have irregular forms: good becomes well, fast remains fast.\n\nAdverb placement is flexible but usually follows the verb or comes at the end of the sentence. For example: 'She plays brilliantly' or 'He hit the ball powerfully.' Be careful not to confuse adjectives and adverbs. After a linking verb like is, are, or looks, use an adjective, not an adverb. We say 'She looks tired' (adjective), not 'She looks tiredly.'",
      examples: [
        "The gymnast performed beautifully. (adverb modifying the verb 'performed')",
        "She is a beautiful gymnast. (adjective modifying the noun 'gymnast')",
        "He ran quickly to the finish line. (adverb of manner)",
        "She looked exhausted after the marathon. (adjective after linking verb 'looked')",
      ],
      modelText:
        "When Sari Dewi steps onto the badminton court, she moves with extraordinary precision. She watches her opponent carefully and reacts swiftly to every shot. Her footwork is impeccable; she glides silently from one corner of the court to the other, positioning herself perfectly for each return. When she strikes the shuttlecock, she does so powerfully yet accurately, sending it to the most difficult angles. Between rallies, she breathes deeply and calmly, maintaining her composure even during the most intense moments of the match. Her opponents often describe playing against her as overwhelming because she seems to anticipate every move before it happens.",
      activities: [
        {
          id: "ga-l4-act-1",
          type: "matching",
          title: "Adjective to Adverb Matching",
          instruction: "Match each adjective on the left with its adverb form on the right.",
          content: {
            type: "matching",
            pairs: [
              { id: "m1", left: "graceful", right: "gracefully" },
              { id: "m2", left: "fierce", right: "fiercely" },
              { id: "m3", left: "precise", right: "precisely" },
              { id: "m4", left: "powerful", right: "powerfully" },
              { id: "m5", left: "good", right: "well" },
            ],
            explanation: "Most adjectives become adverbs by adding -ly. The exception is 'good,' which becomes 'well.'",
          },
          answerKey: {
            answers: { m1: "gracefully", m2: "fiercely", m3: "precisely", m4: "powerfully", m5: "well" },
            explanation: "Add -ly to the adjective. Good is irregular and becomes well.",
          },
          duration: 10,
          level: "remember",
        },
        {
          id: "ga-l4-act-2",
          type: "multiple-choice",
          title: "Adjective or Adverb?",
          instruction: "Choose the correct option to complete each sentence.",
          content: {
            type: "multiple-choice",
            question: "The coach looked ___ at the scoreboard after the final whistle.",
            options: [
              { id: "mc1", text: "disappointing" },
              { id: "mc2", text: "disappointed" },
              { id: "mc3", text: "disappointedly" },
              { id: "mc4", text: "disappointment" },
            ],
            correctId: "mc2",
            explanation: "After the linking verb 'looked,' we need an adjective to describe the coach's emotional state. 'Disappointed' is the correct adjective form.",
          },
          answerKey: {
            answers: { "mc2": "correct" },
            explanation: "Linking verbs (look, feel, seem) take adjectives, not adverbs. The coach felt disappointed, not disappointingly.",
          },
          duration: 10,
          level: "understand",
        },
        {
          id: "ga-l4-act-3",
          type: "writing-task",
          title: "Action Scene Description",
          instruction: "Write a 5-sentence description of an athlete in the middle of a competition, using at least 4 different adverbs of manner.",
          content: {
            type: "writing-task",
            context: "You are a sports commentator describing a live moment in a game.",
            purpose: "To use adverbs of manner to make action descriptions vivid.",
            audience: "Viewers watching the broadcast.",
            constraints: ["Write exactly 5 sentences", "Use at least 4 adverbs of manner", "Describe an athlete in action during a game", "Use simple present tense for live commentary effect"],
            checklist: ["4+ adverbs of manner used", "Adverbs placed correctly", "Vivid and engaging description", "Simple present tense"],
          },
          answerKey: {
            answers: {},
            explanation: "Open-ended writing task.",
            openEnded: true,
            sampleResponse: "The basketball player dribbles skillfully past two defenders. He moves quickly toward the hoop and jumps powerfully. He shoots the ball precisely into the net. The crowd cheers wildly as the buzzer sounds. He celebrates calmly, already focused on the next play.",
            lookFor: ["adverb variety", "correct adverb placement", "vivid action imagery"],
          },
          duration: 20,
          level: "create",
        },
      ],
      teacherNotes: {
        objective: "Students will correctly form and use adverbs of manner to enhance descriptive writing.",
        time: "50 minutes",
        grouping: "Whole class, pair matching game, individual writing",
        teacherPrompt: "Start with a quick game: give students an adjective and have them shout out the adverb form. Then move to the placement rules.",
        expectedResponse: "Students can form most -ly adverbs correctly and place them in appropriate positions in sentences.",
        commonDifficulty: "Using adverbs after linking verbs instead of adjectives. Use the 'feel/look/seem = adjective' rule.",
        followUp: "Have students revise their earlier writing from lesson 3 to include more adverbs of manner.",
      },
    },
  ],
  caseStudy: {
    type: "case-study",
    context: "Putri Aisyah is a 16-year-old long-distance runner from Bandung. She has won three regional championships this year and is training for the national event. However, her exam period is approaching, and she is struggling to balance six hours of daily training with her schoolwork. Her parents are worried about her grades, and her coach insists she cannot reduce training if she wants to win. Putri has been skipping meals and sleeping only five hours a night to fit everything in. She has started feeling fatigued during training and her times have gotten slower, not faster.",
    problem: "Putri is experiencing the consequences of poor time management and overtraining. She needs to find a way to balance her athletic and academic commitments without sacrificing her health.",
    evidence: [
      "Putri trains six hours daily and sleeps only five hours per night.",
      "She has been skipping meals due to lack of time.",
      "Her race times are getting slower despite increased training volume.",
      "Her parents are concerned about her academic performance.",
      "Her coach expects continued full training despite exam preparation.",
    ],
    questions: [
      "What specific changes could Putri make to her daily schedule to improve the balance between training and studying?",
      "How might lack of sleep and proper nutrition be affecting her athletic performance?",
      "What advice would you give Putri's coach about adjusting the training plan during exam season?",
      "Write a short description of Putri's situation, focusing on the consequences of overtraining using descriptive language.",
    ],
  },
  evaluation: [
    {
      id: "ga-eval-1",
      type: "multiple-choice",
      title: "Grammar and Vocabulary Quiz",
      instruction: "Choose the best answer for each question.",
      content: {
        type: "multiple-choice",
        question: "Which sentence correctly uses an adverb of manner?",
        options: [
          { id: "ev1a", text: "She ran quick to the finish line." },
          { id: "ev1b", text: "She ran quickly to the finish line." },
          { id: "ev1c", text: "She quickly ran the finish line." },
          { id: "ev1d", text: "She quick ran to the finish line." },
        ],
        correctId: "ev1b",
        explanation: "The adverb 'quickly' correctly modifies the verb 'ran.' Adverbs of manner typically follow the verb or come at the end of the clause.",
      },
      answerKey: {
        answers: { "ev1b": "correct" },
        explanation: "Adverbs modify verbs and usually come after the verb or at the end of the clause.",
      },
      duration: 10,
      level: "remember",
    },
    {
      id: "ga-eval-2",
      type: "writing-task",
      title: "Descriptive Writing Assessment",
      instruction: "Write a descriptive paragraph (120-180 words) about an athlete of your choice.",
      content: {
        type: "writing-task",
        context: "You are submitting a piece for a school yearbook feature on inspirational athletes.",
        purpose: "To demonstrate mastery of descriptive writing techniques learned in this chapter.",
        audience: "Students and teachers at your school.",
        constraints: ["Include a topic sentence", "Use at least 6 adjectives", "Use at least 3 adverbs", "Include a concluding sentence", "120-180 words"],
        checklist: ["Topic sentence present", "6+ adjectives", "3+ adverbs", "Clear paragraph structure", "Word count appropriate"],
        rubric: [
          { criterion: "Vocabulary range", levels: ["Limited", "Adequate", "Good", "Excellent"] },
          { criterion: "Grammar accuracy", levels: ["Frequent errors", "Some errors", "Mostly correct", "Accurate"] },
          { criterion: "Coherence and structure", levels: ["Disorganized", "Somewhat clear", "Well-organized", "Highly effective"] },
        ],
      },
      answerKey: {
        answers: {},
        explanation: "Assessed using the provided rubric.",
        openEnded: true,
        lookFor: ["variety in adjective choices", "correct adverb formation", "logical structure", "vivid imagery"],
      },
      duration: 25,
      level: "create",
    },
    {
      id: "ga-eval-3",
      type: "true-false",
      title: "Descriptive Writing Concepts",
      instruction: "Write T (True) or F (False) for each statement.",
      content: {
        type: "true-false",
        statements: [
          { id: "tf1", text: "An adjective describes a verb, while an adverb describes a noun.", correct: false },
          { id: "tf2", text: "The simple present tense is used to describe habits and routines.", correct: true },
          { id: "tf3", text: "Frequency adverbs like 'always' and 'never' come at the end of a sentence.", correct: false },
          { id: "tf4", text: "A descriptive paragraph should have a topic sentence and supporting details.", correct: true },
        ],
        explanation: "Statement 1 is false: adjectives describe nouns, adverbs describe verbs. Statement 3 is false: frequency adverbs usually come before the main verb.",
      },
      answerKey: {
        answers: { tf1: "false", tf2: "true", tf3: "false", tf4: "true" },
        explanation: "Review the rules for adjective vs. adverb usage and frequency adverb placement.",
      },
      duration: 5,
      level: "remember",
    },
    {
      id: "ga-eval-4",
      type: "fill-blank",
      title: "Complete the Description",
      instruction: "Fill in the blanks to complete the descriptive paragraph.",
      content: {
        type: "fill-blank",
        sentence: "Rani is a ___ tennis player who trains ___ every day. She is known for her ___ serve and ___ footwork. Her opponents find her ___ to play against because she remains ___ under pressure.",
        blanks: [
          { id: "fb1", position: 1, acceptedAnswers: ["talented", "gifted", "skilled", "remarkable"] },
          { id: "fb2", position: 2, acceptedAnswers: ["diligently", "hard", "faithfully", "consistently"] },
          { id: "fb3", position: 3, acceptedAnswers: ["powerful", "strong", "devastating", "impressive"] },
          { id: "fb4", position: 4, acceptedAnswers: ["quick", "fast", "agile", "precise"] },
          { id: "fb5", position: 5, acceptedAnswers: ["difficult", "challenging", "tough", "formidable"] },
          { id: "fb6", position: 6, acceptedAnswers: ["calm", "focused", "composed", "relaxed"] },
        ],
        explanation: "The paragraph requires adjectives and adverbs that logically describe a talented tennis player and her qualities.",
      },
      answerKey: {
        answers: { fb1: "talented", fb2: "diligently", fb3: "powerful", fb4: "quick", fb5: "difficult", fb6: "calm" },
        explanation: "Any appropriate adjectives or adverbs that create a coherent description are acceptable.",
      },
      duration: 10,
      level: "apply",
    },
  ],
  remedial: [
    {
      id: "ga-rem-1",
      type: "matching",
      title: "Review: Adjective-Adverb Pairs",
      instruction: "Match each word with its correct form. This activity helps review basic adjective and adverb formation.",
      content: {
        type: "matching",
        pairs: [
          { id: "rm1", left: "slow", right: "slowly" },
          { id: "rm2", left: "happy", right: "happily" },
          { id: "rm3", left: "fast", right: "fast" },
          { id: "rm4", left: "careful", right: "carefully" },
          { id: "rm5", left: "good", right: "well" },
        ],
        explanation: "Most adjectives add -ly to become adverbs. Fast and good are irregular.",
      },
      answerKey: {
        answers: { rm1: "slowly", rm2: "happily", rm3: "fast", rm4: "carefully", rm5: "well" },
        explanation: "Review the rules: most add -ly, but fast stays fast and good becomes well.",
      },
      duration: 10,
      level: "remember",
    },
    {
      id: "ga-rem-2",
      type: "fill-blank",
      title: "Simple Present Practice",
      instruction: "Fill in each blank with the correct simple present form of the verb in parentheses.",
      content: {
        type: "fill-blank",
        sentence: "She (train) ___ every morning. He (not/miss) ___ a single practice. The team (play) ___ on Saturdays. She (always/do) ___ her warm-up exercises first.",
        blanks: [
          { id: "rp1", position: 1, acceptedAnswers: ["trains"] },
          { id: "rp2", position: 2, acceptedAnswers: ["does not miss", "doesn't miss", "never misses"] },
          { id: "rp3", position: 3, acceptedAnswers: ["plays"] },
          { id: "rp4", position: 4, acceptedAnswers: ["always does"] },
        ],
        explanation: "Remember to add -s to verbs with he/she/it subjects. For negative forms, use does not or doesn't.",
      },
      answerKey: {
        answers: { rp1: "trains", rp2: "doesn't miss", rp3: "plays", rp4: "always does" },
        explanation: "He/she/it takes the -s form. For negatives, use does not + base verb.",
      },
      duration: 10,
      level: "understand",
    },
  ],
  enrichment: [
    {
      id: "ga-enr-1",
      type: "discussion",
      title: "Athlete Biography Research",
      instruction: "Research a lesser-known athlete and prepare a 2-minute oral presentation describing them.",
      content: {
        type: "discussion",
        prompt: "Find an athlete from a country other than your own. Prepare to describe their appearance, personality, training habits, and achievements. Use at least 8 different adjectives and 4 adverbs in your presentation.",
        thinkingTime: 10,
        pairInstruction: "Present your athlete to a partner and take notes on their presentation.",
        shareOutPrompt: "Which athletes were the most interesting? What adjectives stood out?",
      },
      answerKey: {
        answers: {},
        explanation: "Assess based on vocabulary range, accuracy, and presentation clarity.",
        openEnded: true,
        lookFor: ["diverse vocabulary", "accurate facts", "clear delivery", "creative descriptions"],
      },
      duration: 20,
      level: "create",
    },
    {
      id: "ga-enr-2",
      type: "writing-task",
      title: "Create Your Own Athlete",
      instruction: "Invent a fictional athlete and write a full descriptive profile (200-250 words).",
      content: {
        type: "writing-task",
        context: "You are creating a character for a sports magazine feature about fictional athletes.",
        purpose: "To practice descriptive writing with complete creative freedom.",
        audience: "Magazine readers who enjoy fiction.",
        constraints: ["Invent a name, sport, country, and personality", "Use at least 10 adjectives", "Use at least 5 adverbs", "Include physical description, personality, habits, and achievements", "200-250 words"],
        checklist: ["Original character", "10+ adjectives", "5+ adverbs", "All categories covered", "Engaging and vivid"],
        rubric: [
          { criterion: "Creativity", levels: ["Minimal", "Some", "Good", "Highly original"] },
          { criterion: "Language use", levels: ["Limited", "Adequate", "Good", "Excellent"] },
          { criterion: "Detail and coherence", levels: ["Sparse", "Some detail", "Well-developed", "Richly detailed"] },
        ],
      },
      answerKey: {
        answers: {},
        explanation: "Assessed using the provided rubric.",
        openEnded: true,
        lookFor: ["originality", "vocabulary range", "vivid imagery", "logical structure"],
      },
      duration: 30,
      level: "create",
    },
  ],
  reflection: [
    {
      type: "reflection",
      prompts: [
        { id: "ga-ref-1", question: "What was the most important thing you learned about descriptive writing in this chapter?", type: "understanding" },
        { id: "ga-ref-2", question: "Which activity did you find most challenging and why?", type: "difficulty" },
        { id: "ga-ref-3", question: "How can you use descriptive writing skills outside of English class?", type: "application" },
        { id: "ga-ref-4", question: "What would you like to improve about your descriptive writing in the next chapter?", type: "next-step" },
      ],
    },
  ],
};
